# https://hub.docker.com/r/plexinc/pms-docker

version: "3.9"
services:
  plex:
    image: plexinc/pms-docker:latest
    pull_policy: always
    container_name: plex
    hostname: plex.internal
    environment:
      TZ: "America/New_York"
      PLEX_CLAIM: "claim-abcdefg"  # https://www.plex.tv/claim/
    ports:
      - "32400:32400"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '4'
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 1m
    # devices:
    #   - /dev/dri:/dev/dri
    tmpfs:
      - /transcode
    volumes:
      - ./volumes/plex/config:/config
      # :ro makes this mount read-only
      # remove :ro to allow Plex to delete files and to store optimized versions alongside video files
      - /path/to/movies:/mnt/movies:ro
