services:
  lama-cleaner:
    image: cwq1913/lama-cleaner:cpu-0.26.1
    pull_policy: if_not_present
    container_name: lama-cleaner
    hostname: lama-cleaner.internal
    restart: unless-stopped
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: "4G"
          cpus: "4"
    volumes:
      - "./volumes/lama-cleaner/torch_cache:/root/.cache/torch"
      - "./volumes/lama-cleaner/huggingface_cache:/root/.cache/huggingface"
    command: lama-cleaner --device=cpu --port=8080 --host=0.0.0.0 --model=fcf
