# https://hub.docker.com/r/jellyfin/jellyfin

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    pull_policy: if_not_present
    container_name: jellyfin
    hostname: jellyfin.internal
    ports:
      - 8096:8096/tcp  # http
      - 8920:8920/tcp  # https
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: "4G"
          cpus: 4
    # see https://jellyfin.org/docs/general/administration/hardware-acceleration.html
    # devices:
    #   - /dev/dri:/dev/dri
    tmpfs:
      - /config/transcodes
    volumes:
      - ./volumes/jellyfin/cache:/cache
      - ./volumes/jellyfin/config:/config
      - /path/to/movies:/mnt/movies:ro
