# https://hub.docker.com/r/syncthing/syncthing
# https://github.com/syncthing/syncthing/blob/main/README-Docker.md

version: "3.9"
services:
  syncthing:
    image: syncthing/syncthing:latest
    pull_policy: if_not_present
    container_name: syncthing
    hostname: syncthing.internal
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: "1G"
          cpus: "2"
    ports:
      - 8384:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./volumes/syncthing/syncthing:/var/syncthing
      
      # Mount paths you want to sync using Syncthing
      - /path/on/host:/path/in/container
